apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  name: s2i-jboss-as
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/myproject/s2i-jboss-as:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
